### ISSUE TITLE
Progress on open-sourcing?

### ISSUE THREAD

**Issue by mara004** [Charltsing/JBIG2Viewer#1]
The project's Readme says

> JBIG2Viewer is currently not an open source tool, and the reason for not being open source is that it is currently under testing. In the near future, after passing the testing, I will open source this project.

I'm wondering if there's any progress on this intended source disclosure?
Even if the program is not fully tested or correct yet, it would nevertheless be nice to have the source code available.
Hardly any open source project can be called exactly bug-free or finished. If the project's mature enough to publish an executable you can also publish the code IMHO.

**Comment by Charltsing** [comment]
maybe 3 years

What features are you interested in ?

**Comment by mara004** [comment]
> maybe 3 years

That's really long, isn't it?

> What features are you interested in ?

I'm a Python PDF backend dev dealing with image extraction, and would like to extract images without transcoding, but no tool I'm aware of seems to be able to actually display standalone JBIG2 files, except perhaps this.
Currently most PDF engines just transcode JBIG2 for this reason, but from a programmatic POV that's really unfortunate.
So I've been looking for answers to the problem, and given the name `JBIG2Viewer` I guessed this might be.

**Comment by mara004** [comment]
I've already been wondering if the best way to "extract" JBIG2 from PDF might be to just isolate the image in a new PDF, seeing as JBIG2 is well-supported with a PDF wrapper, but not standalone. However, that wouldn't strictly count as extraction anymore.

**Comment by Charltsing** [comment]
If you want to "extract" JBIG2 from PDF, you can try [this](https://github.com/wmjordan/PDFPatcher/blob/acd7cf13e9e28f6186b5dd5989ddd3141f9013d8/App/Processor/Imaging/ImageInfo.cs#L111)

**Comment by mara004** [comment]
> If you want to "extract" JBIG2 from PDF, you can try [this](https://github.com/wmjordan/PDFPatcher/blob/acd7cf13e9e28f6186b5dd5989ddd3141f9013d8/App/Processor/Imaging/ImageInfo.cs#L111)

I'm aware how to get the main and global segments streams, but this code again just decodes the JBIG2 data (`outBuf = Processor.Imaging.JBig2Decoder.Decode(decodedBytes, globals);`), so it'll have to re-encode later or save uncompressed.
However, my intent was to extract, and be able to use, the original data without losing quality or compression.

As discussed above, I figured this is unfortunately not practical, due to lack of support for standalone JBIG2 in end user image applications, which seems to be the elephant in the room here.

**Comment by mara004** [comment]
For another thing, I'm not sure yet how one would merge the PDF format's split streams and metadata back into a standalone file, but this should be doable in principle.

Anyway, I just found a pointer in `jbig2enc`'s Readme that standalone JBIG2 can be displayed by a program called `STDU Viewer` (though it's also proprietary). I'll try this, and maybe find an OSS program some day or try to write my own viewer script around `jbig2dec` or something.

**Comment by Charltsing** [comment]
you can convert jbig2 to pbm, it is lossless.

Some codes are as follows :
CTXJBig2Image CTXImage = JBIG2Codec.Instance.Decode_stream(jbig2stream, null, out IntPtr CTXImagePtr);
JBig2Image Image = (JBig2Image)Marshal.PtrToStructure(CTXImage.ImagePtr, typeof(JBig2Image));
byte[] pbmdata = Image.GetDataCopy();
byte[] pbmbytes = PnmHelper.ExportPBM(pbmdata, Image.Width, Image.Height);
Image bmp = PnmHelper.Load(pbmbytes);

**Comment by mara004** [comment]
> you can convert jbig2 to pbm, it is lossless.

Well, yes it doesn't lose quality, but it loses the compression, which is the whole point of JBIG2.
Also, decoding is a performance problem - we should always prefer direct extraction where possible.

**Comment by Charltsing** [comment]
> > you can convert jbig2 to pbm, it is lossless.
> 
> Well, yes it doesn't lose quality, but it loses the compression, which is the whole point of JBIG2. Also, decoding is a performance problem - we should always prefer direct extraction where possible.

导出图像的目的肯定是为了编辑，但是jbig2图像编辑需要被转成通用格式才能编辑，例如pnm、bmp。所以要么导出原始格式的Jbig2数据，但是只能查看。要么导出之后转换为pnm，然后你可以编辑。你只能在这两者之间做选择。每种图像格式都是这样处理的。

The purpose of exporting images is definitely for editing, but jbig2 image editing needs to be converted to a universal format for editing, such as pnm, bmp. So either export the Jbig2 data in its original format, but only view it. Either export it and convert it to PNM, and then you can edit it. You can only choose between these two.Each image format is processed in this way, including jpg

you can convert pbm to jbig2，after edited

**Comment by mara004** [comment]
> The purpose of exporting images is definitely for editing

Well for me it isn't - it's more about detaching from the PDF wrapper, and what will be done with the image depends on the caller (e.g. storing/viewing, editing). The image is just preserved in its original form, which is the most flexible.
The caller can decode if desired.

> you can convert pbm to jbig2，after edited

This would lead to generation loss.

I doubt if it's good to edit lossy images directly, you had perhaps better overdraw in the PDF (as long as it's not about confidential info or something).

**Comment by Charltsing** [comment]
JBig2支持有损压缩和无损压缩，大部分时候，有损压缩和无损压缩在解码之后看起来没什么区别。所以，我们可以在解码之后使用Pbm来处理JBig2图像，然后采用无损压缩转成JBig2文件格式，这不会降低图像质量。
当然，你也可以直接从PDF中提取JBig2原始数据，但这没什么意义，因为不会有图像工具支持这个格式。少有的那几个支持它的图像工具，也是将图像转成Pbm或者Bmp进行处理。

JBig2 supports lossy compression and lossless compression, and most of the time, lossy compression and lossless compression look no different after decoding. So, we can use Pbm to process JBig2 images after decoding, and then use lossless compression to convert them into JBig2 file format, which will not reduce image quality.
Of course, you can also directly extract JBig2 raw data from PDF, but this is not meaningful because there will be no image tools supporting this format. The few image tools that support it also convert images into Pbm or Bmp for processing

some code as follow (save bmp to JBig2):
byte[] sourcedata = BitmapHelper.BitmapTo1ppPIXuint32Data(bmp);
int width = bmp.Width;
int height = bmp.Height;                        
bool success = JBIG2Codec.Instance.Encode2file(sourcedata, width, height, fileName);

sourcedata  is  pbm data

**Comment by mara004** [comment]
> and then use lossless compression to convert them into JBig2 file format, which will not reduce image quality.

This adds a processing step, will lose the original encoding config and most probably increase file size.
Though yes, if you actually mean to edit the image there's no other way than re-encode.
However, I'm concerned about use cases that do not actually edit the image, e.g. just isolating it, or moving into a different container.

> but this is not meaningful because there will be no image tools supporting this format

True,[^1] and that's what I've been discussing above.
However, AFAICS that's not a problem with the format itself, but with its adoption. Technically JBIG2 is a standalone format just like JPG etc. Possible reasons for the low adoption might include patent concerns with encoders, at least for the OSS world.

Anyway, seems like I misunderstood this program's purpose after all.
I think I've found my resolution, and this discussion is kind of leading into nowhere now, so let's please wrap it up.

[^1]: well, not none, but very few

**Comment by Charltsing** [comment]
just isolating the image, or moving into a different container.
---PDF 并不保存JBig2图像，它保存的是Jbig2globals和pageRawBytes。所以如果你想移动或者提取图像，只需要提取Jbig2globals和pageRawBytes，但是你不需要将这两个数据段合并为JBig2图像文件，因为那没有意义。

**Comment by mara004** [comment]
Fair enough, you could transfer directly in that case.

I was just thinking of a generic API: Saving as a standalone file as a standard way to transfer the two streams and the metadata would allow for integration in a universal pipeline with receiving tools like img2pdf.
Anyway, I acknowledge the applicability would be limited as long as it's not a more widely used format.
